//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACW_08346_483446_Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/HELLO", ReplyAction="http://tempuri.org/IService/HELLOResponse")]
        string HELLO(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/HELLO", ReplyAction="http://tempuri.org/IService/HELLOResponse")]
        System.Threading.Tasks.Task<string> HELLOAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SORT", ReplyAction="http://tempuri.org/IService/SORTResponse")]
        string SORT(int number, string[] value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SORT", ReplyAction="http://tempuri.org/IService/SORTResponse")]
        System.Threading.Tasks.Task<string> SORTAsync(int number, string[] value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PUBKEY", ReplyAction="http://tempuri.org/IService/PUBKEYResponse")]
        string PUBKEY();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PUBKEY", ReplyAction="http://tempuri.org/IService/PUBKEYResponse")]
        System.Threading.Tasks.Task<string> PUBKEYAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ENC", ReplyAction="http://tempuri.org/IService/ENCResponse")]
        string ENC(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ENC", ReplyAction="http://tempuri.org/IService/ENCResponse")]
        System.Threading.Tasks.Task<string> ENCAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SHA1", ReplyAction="http://tempuri.org/IService/SHA1Response")]
        string SHA1(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SHA1", ReplyAction="http://tempuri.org/IService/SHA1Response")]
        System.Threading.Tasks.Task<string> SHA1Async(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SHA256", ReplyAction="http://tempuri.org/IService/SHA256Response")]
        string SHA256(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SHA256", ReplyAction="http://tempuri.org/IService/SHA256Response")]
        System.Threading.Tasks.Task<string> SHA256Async(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SIGN", ReplyAction="http://tempuri.org/IService/SIGNResponse")]
        string SIGN(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SIGN", ReplyAction="http://tempuri.org/IService/SIGNResponse")]
        System.Threading.Tasks.Task<string> SIGNAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ACW_08346_483446_Client.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ACW_08346_483446_Client.ServiceReference.IService>, ACW_08346_483446_Client.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HELLO(int id) {
            return base.Channel.HELLO(id);
        }
        
        public System.Threading.Tasks.Task<string> HELLOAsync(int id) {
            return base.Channel.HELLOAsync(id);
        }
        
        public string SORT(int number, string[] value) {
            return base.Channel.SORT(number, value);
        }
        
        public System.Threading.Tasks.Task<string> SORTAsync(int number, string[] value) {
            return base.Channel.SORTAsync(number, value);
        }
        
        public string PUBKEY() {
            return base.Channel.PUBKEY();
        }
        
        public System.Threading.Tasks.Task<string> PUBKEYAsync() {
            return base.Channel.PUBKEYAsync();
        }
        
        public string ENC(string message) {
            return base.Channel.ENC(message);
        }
        
        public System.Threading.Tasks.Task<string> ENCAsync(string message) {
            return base.Channel.ENCAsync(message);
        }
        
        public string SHA1(string message) {
            return base.Channel.SHA1(message);
        }
        
        public System.Threading.Tasks.Task<string> SHA1Async(string message) {
            return base.Channel.SHA1Async(message);
        }
        
        public string SHA256(string message) {
            return base.Channel.SHA256(message);
        }
        
        public System.Threading.Tasks.Task<string> SHA256Async(string message) {
            return base.Channel.SHA256Async(message);
        }
        
        public string SIGN(string message) {
            return base.Channel.SIGN(message);
        }
        
        public System.Threading.Tasks.Task<string> SIGNAsync(string message) {
            return base.Channel.SIGNAsync(message);
        }
    }
}
